CREATE TABLE animal
(
    id               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_animal  VARCHAR(255)                         NOT NULL,
    nome_provisorio  VARCHAR(255)                         NOT NULL,
    idade_estimada   INT                                  NOT NULL,
    raca             VARCHAR(255)                         NOT NULL,
    data_entrada     TIMESTAMP                            NOT NULL,
    data_adocao      TIMESTAMP,
    condicao_chegada VARCHAR(255)                         NOT NULL,
    nome_recebedor   VARCHAR(255)                         NOT NULL,
    data_obito       TIMESTAMP,
    porte            VARCHAR(255)                         NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);