server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profile:
      activate: native
  data:
    mongodb:
      uri: mongodb+srv://d4vyl0pes:JTd06pa0EC1sfIPl@cluster0.9olprog.mongodb.net/
      database: cliente
      auto-index-creation: true

application-version: 1.0